PMS/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMS.Data;
using PMS.Models;

namespace PMS.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customers
                .FirstOrDefaultAsync(m => m.CustomerID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,CustomerFullname,Gender,Age,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerID,CustomerFullname,Gender,Age,Phone")] Customer customer)
        {
            if (id != customer.CustomerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.customers
                .FirstOrDefaultAsync(m => m.CustomerID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.customers.FindAsync(id);
            _context.customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.customers.Any(e => e.CustomerID == id);
        }
    }
}

PMS/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMS.Data;
using PMS.Models;

namespace PMS.Controllers
{
    public class MedicinesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MedicinesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Medicines
        public async Task<IActionResult> Index()
        {
            return View(await _context.medicines.ToListAsync());
        }

        // GET: Medicines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicine = await _context.medicines
                .FirstOrDefaultAsync(m => m.MedicineID == id);
            if (medicine == null)
            {
                return NotFound();
            }

            return View(medicine);
        }

        // GET: Medicines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedicineID,MedcineCat,MedicineName,Description")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicine);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicine);
        }

        // GET: Medicines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicine = await _context.medicines.FindAsync(id);
            if (medicine == null)
            {
                return NotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedicineID,MedcineCat,MedicineName,Description")] Medicine medicine)
        {
            if (id != medicine.MedicineID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicineExists(medicine.MedicineID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicine);
        }

        // GET: Medicines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicine = await _context.medicines
                .FirstOrDefaultAsync(m => m.MedicineID == id);
            if (medicine == null)
            {
                return NotFound();
            }

            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medicine = await _context.medicines.FindAsync(id);
            _context.medicines.Remove(medicine);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicineExists(int id)
        {
            return _context.medicines.Any(e => e.MedicineID == id);
        }
    }
}

PMS/Controllers/purchasingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMS.Data;
using PMS.Models;

namespace PMS.Controllers
{
    public class purchasingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public purchasingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: purchasings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.purchasing.Include(p => p.Customer).Include(p => p.Medicine);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: purchasings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasing = await _context.purchasing
                .Include(p => p.Customer)
                .Include(p => p.Medicine)
                .FirstOrDefaultAsync(m => m.purchasingID == id);
            if (purchasing == null)
            {
                return NotFound();
            }

            return View(purchasing);
        }

        // GET: purchasings/Create
        public IActionResult Create()
        {
            ViewData["CustomerID"] = new SelectList(_context.customers, "CustomerID", "CustomerFullname");
            ViewData["MedicineID"] = new SelectList(_context.medicines, "MedicineID", "MedicineName");
            return View();
        }

        // POST: purchasings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("purchasingID,Price,Date,CustomerID,MedicineID")] purchasing purchasing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(purchasing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerID"] = new SelectList(_context.customers, "CustomerID", "CustomerID", purchasing.CustomerID);
            ViewData["MedicineID"] = new SelectList(_context.medicines, "MedicineID", "MedicineID", purchasing.MedicineID);
            return View(purchasing);
        }

        // GET: purchasings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasing = await _context.purchasing.FindAsync(id);
            if (purchasing == null)
            {
                return NotFound();
            }
            ViewData["CustomerID"] = new SelectList(_context.customers, "CustomerID", "CustomerID", purchasing.CustomerID);
            ViewData["MedicineID"] = new SelectList(_context.medicines, "MedicineID", "MedicineID", purchasing.MedicineID);
            return View(purchasing);
        }

        // POST: purchasings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("purchasingID,Price,Date,CustomerID,MedicineID")] purchasing purchasing)
        {
            if (id != purchasing.purchasingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchasing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!purchasingExists(purchasing.purchasingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerID"] = new SelectList(_context.customers, "CustomerID", "CustomerID", purchasing.CustomerID);
            ViewData["MedicineID"] = new SelectList(_context.medicines, "MedicineID", "MedicineID", purchasing.MedicineID);
            return View(purchasing);
        }

        // GET: purchasings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchasing = await _context.purchasing
                .Include(p => p.Customer)
                .Include(p => p.Medicine)
                .FirstOrDefaultAsync(m => m.purchasingID == id);
            if (purchasing == null)
            {
                return NotFound();
            }

            return View(purchasing);
        }

        // POST: purchasings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var purchasing = await _context.purchasing.FindAsync(id);
            _context.purchasing.Remove(purchasing);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool purchasingExists(int id)
        {
            return _context.purchasing.Any(e => e.purchasingID == id);
        }
    }
}

PMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- DataTables -->
    <link rel="stylesheet" href="~/LayoutDesign/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/LayoutDesign/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/LayoutDesign/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="~/LayoutDesign/dist/css/adminlte.min.css" />
    <link rel="stylesheet" href="~/LayoutDesign/plugins/fontawesome-free/css/all.min.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                @*<li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>*@
            <li class="nav-item d-none d-sm-inline-block">
            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
                <h3>__ Adan Ade Pharmacy</h3>
        </li>
        @*<li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <br class="p">
            <a class="pt-5" style="opacity: .8 ;padding:5px ;margin-top:18px">
                @*<img src="~/LayoutDesign/dist/img/AdminLTELogo.png" />*@
                <img src="~/LayoutDesign/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-size-32 img-circle elevation-3" style="opacity: .8;margin-left:5px;margin-bottom:10px">

                <span class="brand-text font-weight-light  " style="font-size:20px;color:white;font-weight:bold">DAN ADE PHARMACY</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->

                        <li class="nav-item mt-4">
                            <a asp-area="" asp-controller="purchasings" asp-action="Index" class="nav-link">
                                @*<a href="~/../Views/orders1/Index.cshtml" class="nav-link">*@
                                <i class="fa-solid fa-credit-card"></i>
                                <p>
                                    purchasing
                                    @*<span class="right badge badge-danger">New</span>*@
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Customers" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-address-card"></i>
                                <p>
                                    Customers
                                </p>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Medicines" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-briefcase-medical"></i>
                                <p>
                                    Medical
                                    @*<span class="badge badge-info right">6</span>*@
                                </p>
                            </a>

                        </li>



                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-gear"></i>
                                <p>
                                    Settings
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content p-4">

                @RenderBody()

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer text-center">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year All rights reserved.</strong>
        </footer>


        <!-- /.control-sidebar -->
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @* NEW SCRIPT *@
    <script src="~/LayoutDesign/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/LayoutDesign/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/LayoutDesign/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/LayoutDesign/plugins/jszip/jszip.min.js"></script>
    <script src="~/LayoutDesign/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/LayoutDesign/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/LayoutDesign/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="https://kit.fontawesome.com/4782e82238.js" crossorigin="anonymous"></script>
    <!-- AdminLTE App -->
    <script src="~/LayoutDesign/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    @*<script src="~/LayoutDesign/dist/js/demo.js"></script>*@
    <!-- Page specific script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    <!-- Code injected by live-server -->
    <script type="text/javascript">
        // <![CDATA[  <-- For SVG support
        if ('WebSocket' in window) {
            (function () {
                function refreshCSS() {
                    var sheets = [].slice.call(document.getElementsByTagName("link"));
                    var head = document.getElementsByTagName("head")[0];
                    for (var i = 0; i < sheets.length; ++i) {
                        var elem = sheets[i];
                        var parent = elem.parentElement || head;
                        parent.removeChild(elem);
                        var rel = elem.rel;
                        if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
                            var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
                            elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
                        }
                        parent.appendChild(elem);
                    }
                }
                var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
                var address = protocol + window.location.host + window.location.pathname + '/ws';
                var socket = new WebSocket(address);
                socket.onmessage = function (msg) {
                    if (msg.data == 'reload') window.location.reload();
                    else if (msg.data == 'refreshcss') refreshCSS();
                };
                if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
                    console.log('Live reload enabled.');
                    sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
                }
            })();
        }
        else {
            console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
        }

    </script>
</body>
</html>